const CONFIG={1:{big:266.4,reg:439.8,grape:5.94},2:{big:259.0,reg:407.1,grape:5.92},3:{big:256.0,reg:366.1,grape:5.90},4:{big:249.2,reg:322.8,grape:5.83},5:{big:240.1,reg:299.3,grape:5.80},6:{big:219.9,reg:262.1,grape:5.70}};
const symbols=["7️⃣","🤡","🍇","🔔","🍒","🍋","⭐"];const reels=[0,1,2].map(i=>document.getElementById(`reel${i}`));const stops=[0,1,2].map(i=>document.getElementById(`stop${i}`));const el=id=>document.getElementById(id);
let credit=50,bet=0,game=0,medals=0,big=0,reg=0,grape=0,sinceBonus=0,lastPay=0;let spinning=false,reelTimers=[null,null,null],stopped=[true,true,true],finalSymbols=["🍒","🔔","7️⃣"];let auto=false,autoCount=0,soundOn=true,currentSetting=1,pendingPeka=false,pekaTiming="none";
function update(){el("credit").textContent=credit;el("bet").textContent=bet;el("game").textContent=game;el("medals").textContent=medals;el("bigCount").textContent=big;el("regCount").textContent=reg;el("grapeCount").textContent=grape;el("sinceBonus").textContent=sinceBonus;el("lastPay").textContent=lastPay;el("autoCount").textContent=autoCount;el("bonusRate").textContent=(big+reg)>0?`1/${(game/(big+reg)).toFixed(1)}`:"-";el("grapeRate").textContent=grape>0?`1/${(game/grape).toFixed(2)}`:"-";const c=CONFIG[currentSetting];el("oddsText").textContent=`BIG 1/${c.big}　REG 1/${c.reg}`}
function randSym(){return symbols[Math.floor(Math.random()*symbols.length)]}function msg(t){el("message").textContent=t}
function beep(type="beep"){if(!soundOn)return;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;const ctx=new AC(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.connect(gain);gain.connect(ctx.destination);if(type==="gako"){osc.frequency.setValueAtTime(110,ctx.currentTime);osc.frequency.exponentialRampToValueAtTime(55,ctx.currentTime+.13);gain.gain.setValueAtTime(.28,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.24);osc.start();osc.stop(ctx.currentTime+.25)}else if(type==="peka"){osc.frequency.setValueAtTime(880,ctx.currentTime);gain.gain.setValueAtTime(.08,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.16);osc.start();osc.stop(ctx.currentTime+.17)}else{osc.frequency.setValueAtTime(440,ctx.currentTime);gain.gain.setValueAtTime(.04,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.08);osc.start();osc.stop(ctx.currentTime+.09)}}
function lampOn(gako=false){el("lamp").classList.add("on");beep(gako?"gako":"peka")}function lampOff(){el("lamp").classList.remove("on")}
function betOne(){if(spinning||auto)return;if(bet>=3)return msg("BETは3枚までです。");if(credit<=0)return msg("クレジット不足です。RESETしてください。");credit--;bet++;medals--;update()}
function maxBet(){if(spinning||auto)return;while(bet<3&&credit>0){credit--;bet++;medals--}update()}
function decideResult(){const c=CONFIG[currentSetting];const r=Math.random();const pBig=1/c.big,pReg=1/c.reg,pGrape=1/c.grape,pCherry=1/35.5,pBell=1/90;pendingPeka=false;pekaTiming="none";lampOff();if(r<pBig){pendingPeka=true;pekaTiming=Math.random()<.25?"pre":"post";return["7️⃣","7️⃣","7️⃣"]}if(r<pBig+pReg){pendingPeka=true;pekaTiming=Math.random()<.25?"pre":"post";return["🤡","🤡","🤡"]}if(r<pBig+pReg+pGrape)return["🍇","🍇","🍇"];if(r<pBig+pReg+pGrape+pBell)return["🔔","🔔","🔔"];if(r<pBig+pReg+pGrape+pBell+pCherry)return["🍒",randSym(),randSym()];let a=[randSym(),randSym(),randSym()];if(a[0]===a[1]&&a[1]===a[2])a[2]="🍋";return a}
function spin(){if(spinning)return;if(bet<3){if(auto){while(bet<3&&credit>0){credit--;bet++;medals--}}else return msg("3枚BETしてからレバーを叩いてください。")}lastPay=0;spinning=true;stopped=[false,false,false];finalSymbols=decideResult();game++;sinceBonus++;if(auto)autoCount++;if(pekaTiming==="pre"){lampOn(false);msg("先ペカ。ボーナス確定。");if(auto)stopAuto()}else msg(auto?"AUTO中。光るまで回します。":"リール回転中。STOPを押してください。");reels.forEach((reel,i)=>{stops[i].disabled=auto;reelTimers[i]=setInterval(()=>{reel.textContent=randSym()},55)});if(auto){setTimeout(()=>stopReel(0),180);setTimeout(()=>stopReel(1),300);setTimeout(()=>stopReel(2),420)}update()}
function stopReel(i){if(!spinning||stopped[i])return;clearInterval(reelTimers[i]);reels[i].textContent=finalSymbols[i];stopped[i]=true;stops[i].disabled=true;beep();if(stopped.every(Boolean))finish()}
function finish(){spinning=false;bet=0;const[a,b,c]=finalSymbols;if(pekaTiming==="post"){const gako=Math.random()<.5;lampOn(gako);msg(gako?"後ペカ。ガコッ！ボーナス確定。":"後ペカ。ボーナス確定。");if(auto){stopAuto();update();return}}if(a==="7️⃣"&&b==="7️⃣"&&c==="7️⃣"){lastPay=252;credit+=lastPay;medals+=lastPay;big++;sinceBonus=0;msg("BIG BONUS。252枚獲得。")}else if(a==="🤡"&&b==="🤡"&&c==="🤡"){lastPay=96;credit+=lastPay;medals+=lastPay;reg++;sinceBonus=0;msg("REG BONUS。96枚獲得。")}else if(a==="🍇"&&b==="🍇"&&c==="🍇"){lastPay=8;credit+=lastPay;medals+=lastPay;grape++;msg("ぶどう。8枚獲得。")}else if(a==="🔔"&&b==="🔔"&&c==="🔔"){lastPay=10;credit+=lastPay;medals+=lastPay;msg("ベル。10枚獲得。")}else if(a==="🍒"){lastPay=2;credit+=lastPay;medals+=lastPay;msg("チェリー。2枚獲得。")}else{lastPay=0;msg("ハズレ。")}update();if(auto&&!pendingPeka){setTimeout(()=>{if(auto){while(bet<3&&credit>0){credit--;bet++;medals--}update();spin()}},95)}}
function toggleAuto(){if(auto){stopAuto();return}if(spinning)return;auto=true;autoCount=0;el("autoBtn").classList.add("auto");el("autoBtn").textContent="AUTO停止";msg("光るまでAUTO開始。ボーナス告知で停止します。");while(bet<3&&credit>0){credit--;bet++;medals--}update();spin()}
function stopAuto(){auto=false;el("autoBtn").classList.remove("auto");el("autoBtn").textContent="光るまでAUTO"}
function reset(){reelTimers.forEach(t=>clearInterval(t));credit=50;bet=0;game=0;medals=0;big=0;reg=0;grape=0;sinceBonus=0;lastPay=0;autoCount=0;spinning=false;stopped=[true,true,true];finalSymbols=["🍒","🔔","7️⃣"];pendingPeka=false;reels.forEach((r,i)=>r.textContent=finalSymbols[i]);stops.forEach(b=>b.disabled=true);stopAuto();lampOff();msg("設定を選んでMAX BET → レバー。");update()}
el("betBtn").addEventListener("click",betOne);el("maxBetBtn").addEventListener("click",maxBet);el("spinBtn").addEventListener("click",spin);el("autoBtn").addEventListener("click",toggleAuto);el("resetBtn").addEventListener("click",reset);el("soundBtn").addEventListener("click",()=>{soundOn=!soundOn;el("soundBtn").textContent=soundOn?"SOUND ON":"SOUND OFF"});el("settingSelect").addEventListener("change",e=>{currentSetting=Number(e.target.value);update()});stops.forEach((b,i)=>b.addEventListener("click",()=>stopReel(i)));update();
